// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package openapi

// Defines values for ConfigCreateEventEnabled.
const (
	ConfigCreateEventEnabledAlways ConfigCreateEventEnabled = "always"
	ConfigCreateEventEnabledNever  ConfigCreateEventEnabled = "never"
)

// Defines values for ConfigDeleteEventEnabled.
const (
	ConfigDeleteEventEnabledAlways ConfigDeleteEventEnabled = "always"
	ConfigDeleteEventEnabledNever  ConfigDeleteEventEnabled = "never"
)

// Defines values for ConfigUpdateEventEnabled.
const (
	ConfigUpdateEventEnabledAlways ConfigUpdateEventEnabled = "always"
	ConfigUpdateEventEnabledNever  ConfigUpdateEventEnabled = "never"
)

// Defines values for ConfigUpdateEventWatchFieldsAuto.
const (
	All ConfigUpdateEventWatchFieldsAuto = "all"
)

// Defines values for FieldSettingWriteOnCreate.
const (
	FieldSettingWriteOnCreateAlways FieldSettingWriteOnCreate = "always"
	FieldSettingWriteOnCreateNever  FieldSettingWriteOnCreate = "never"
)

// Defines values for FieldSettingWriteOnUpdate.
const (
	FieldSettingWriteOnUpdateAlways FieldSettingWriteOnUpdate = "always"
	FieldSettingWriteOnUpdateNever  FieldSettingWriteOnUpdate = "never"
)

// Defines values for SelectedFieldsAutoConfig.
const (
	SelectedFieldsAll SelectedFieldsAutoConfig = "all"
)

// Defines values for ValueDefaultBooleanApplyOnUpdate.
const (
	ValueDefaultBooleanApplyOnUpdateAlways ValueDefaultBooleanApplyOnUpdate = "always"
	ValueDefaultBooleanApplyOnUpdateNever  ValueDefaultBooleanApplyOnUpdate = "never"
)

// Defines values for ValueDefaultIntegerApplyOnUpdate.
const (
	ValueDefaultIntegerApplyOnUpdateAlways ValueDefaultIntegerApplyOnUpdate = "always"
	ValueDefaultIntegerApplyOnUpdateNever  ValueDefaultIntegerApplyOnUpdate = "never"
)

// Defines values for ValueDefaultStringApplyOnUpdate.
const (
	ValueDefaultStringApplyOnUpdateAlways ValueDefaultStringApplyOnUpdate = "always"
	ValueDefaultStringApplyOnUpdateNever  ValueDefaultStringApplyOnUpdate = "never"
)

// BackfillConfig defines model for BackfillConfig.
type BackfillConfig struct {
	DefaultPeriod DefaultPeriodConfig `json:"defaultPeriod"`
}

// BaseConfigContent defines model for BaseConfigContent.
type BaseConfigContent struct {
	// Module The SaaS module that we are integrating with.
	Module string `json:"module,omitempty"`

	// Provider The SaaS API that we are integrating with.
	Provider *string          `json:"provider,omitempty"`
	Proxy    *BaseProxyConfig `json:"proxy,omitempty"`
	Read     *BaseReadConfig  `json:"read,omitempty"`
	Write    *BaseWriteConfig `json:"write,omitempty"`
}

// BaseProxyConfig defines model for BaseProxyConfig.
type BaseProxyConfig struct {
	Enabled *bool `json:"enabled,omitempty"`

	// UseModule Default is false. If this is set to true, the base URL for the proxy action will be the module's base URL. Otherwise, it is assumed that the base URL is the provider's root base URL.
	UseModule *bool `json:"useModule,omitempty"`
}

// BaseReadConfig defines model for BaseReadConfig.
type BaseReadConfig struct {
	// Objects This is a map of object names to their configuration.
	Objects *map[string]BaseReadConfigObject `json:"objects,omitempty"`
}

// BaseReadConfigObject defines model for BaseReadConfigObject.
type BaseReadConfigObject struct {
	Backfill *BackfillConfig `json:"backfill,omitempty"`

	// Destination The name of the destination that the result should be sent to.
	Destination string `json:"destination,omitempty"`

	// Disabled If this flag is set to true, scheduled reads associated with this object will be paused, and on-demand reads will not be allowed.
	Disabled *bool `json:"disabled,omitempty"`

	// DynamicMappingsInput An array containing all available dynamic field and value mappings for this installation, provided by the InstallIntegration component. This array represents the complete set of possible mappings, regardless of which ones are currently selected. The actual selected mappings are stored separately in the selectedFieldMappings property.
	DynamicMappingsInput *DynamicMappingsInput `json:"dynamicMappingsInput,omitempty"`

	// ObjectName The name of the object to read from.
	ObjectName *string `json:"objectName,omitempty" validate:"required"`

	// Schedule The schedule for reading the object, in cron syntax.
	Schedule string `json:"schedule,omitempty"`

	// SelectedFieldMappings This is a map of mapToNames to field names. (A mapTo name is the name the builder wants to map a field to when it lands in their destination.)
	SelectedFieldMappings *map[string]string `json:"selectedFieldMappings,omitempty"`

	// SelectedFields This is a map of field names to booleans indicating whether they should be read. If a field is already included in `selectedFieldMappings`, it does not need to be included here.
	SelectedFields *map[string]bool `json:"selectedFields,omitempty"`

	// SelectedFieldsAuto If selectedFieldsAuto is set to all, all fields will be read.
	SelectedFieldsAuto *SelectedFieldsAutoConfig `json:"selectedFieldsAuto,omitempty"`

	// SelectedValueMappings This is a map of field names to their value mappings.
	SelectedValueMappings map[string]SelectedValueMappings `json:"selectedValueMappings,omitempty"`
}

// BaseSubscribeConfig defines model for BaseSubscribeConfig.
type BaseSubscribeConfig struct {
	Objects *map[string]BaseSubscribeConfigObject `json:"objects,omitempty"`
}

// BaseSubscribeConfigObject defines model for BaseSubscribeConfigObject.
type BaseSubscribeConfigObject struct {
	CreateEvent *ConfigCreateEvent `json:"createEvent,omitempty"`
	DeleteEvent *ConfigDeleteEvent `json:"deleteEvent,omitempty"`

	// Destination The name of the destination that the result should be sent to.
	Destination string `json:"destination"`

	// InheritFieldsAndMappings Whether to inherit fields and mappings from the read config.
	InheritFieldsAndMappings bool `json:"inheritFieldsAndMappings"`

	// ObjectName The name of the object to subscribe to.
	ObjectName  string             `json:"objectName" validate:"required"`
	UpdateEvent *ConfigUpdateEvent `json:"updateEvent,omitempty"`
}

// BaseWriteConfig defines model for BaseWriteConfig.
type BaseWriteConfig struct {
	// Objects This is a map of object names to their configuration.
	Objects *map[string]BaseWriteConfigObject `json:"objects,omitempty"`
}

// BaseWriteConfigObject defines model for BaseWriteConfigObject.
type BaseWriteConfigObject struct {
	// ObjectName The name of the object to write to.
	ObjectName string `json:"objectName" validate:"required"`

	// SelectedFieldSettings This is a map of field names to their settings.
	SelectedFieldSettings map[string]FieldSetting `json:"selectedFieldSettings,omitempty"`

	// SelectedValueDefaults This is a map of field names to default values. These values will be used when writing to the object.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	SelectedValueDefaults map[string]ValueDefault `json:"selectedValueDefaults,omitempty"`
}

// ConfigContent defines model for ConfigContent.
type ConfigContent struct {
	// Module The SaaS module that we are integrating with.
	Module string `json:"module,omitempty"`

	// Provider The SaaS API that we are integrating with.
	Provider  string           `json:"provider"`
	Proxy     *BaseProxyConfig `json:"proxy,omitempty"`
	Read      *ReadConfig      `json:"read,omitempty"`
	Subscribe *SubscribeConfig `json:"subscribe,omitempty"`
	Write     *WriteConfig     `json:"write,omitempty"`
}

// ConfigCreateEvent defines model for ConfigCreateEvent.
type ConfigCreateEvent struct {
	// Enabled Conditions to enable create events.
	Enabled ConfigCreateEventEnabled `json:"enabled" validate:"oneof=always never"`
}

// ConfigCreateEventEnabled Conditions to enable create events.
type ConfigCreateEventEnabled string

// ConfigDeleteEvent defines model for ConfigDeleteEvent.
type ConfigDeleteEvent struct {
	// Enabled Conditions to enable delete events.
	Enabled ConfigDeleteEventEnabled `json:"enabled" validate:"oneof=always never"`
}

// ConfigDeleteEventEnabled Conditions to enable delete events.
type ConfigDeleteEventEnabled string

// ConfigUpdateEvent defines model for ConfigUpdateEvent.
type ConfigUpdateEvent struct {
	// Enabled Conditions to enable update events.
	Enabled ConfigUpdateEventEnabled `json:"enabled" validate:"oneof=always never"`

	// RequiredWatchFields The fields that should be watched.
	RequiredWatchFields *[]string `json:"requiredWatchFields,omitempty"`

	// WatchFieldsAuto Whether to watch fields all fields automatically.
	WatchFieldsAuto *ConfigUpdateEventWatchFieldsAuto `json:"watchFieldsAuto,omitempty"`
}

// ConfigUpdateEventEnabled Conditions to enable update events.
type ConfigUpdateEventEnabled string

// ConfigUpdateEventWatchFieldsAuto Whether to watch fields all fields automatically.
type ConfigUpdateEventWatchFieldsAuto string

// DefaultPeriodConfig defines model for DefaultPeriodConfig.
type DefaultPeriodConfig struct {
	// Days Number of days in past to backfill from. 0 is no backfill. e.g) if 10, then backfill last 10 days of data. Required if fullHistory is not set.
	Days *int `json:"days,omitempty" validate:"required_without=FullHistory,omitempty,min=0"`

	// FullHistory If true, backfill all history. Required if days is not set.
	FullHistory *bool `json:"fullHistory,omitempty" validate:"required_without=Days"`
}

// DynamicMappingsInput An array containing all available dynamic field and value mappings for this installation, provided by the InstallIntegration component. This array represents the complete set of possible mappings, regardless of which ones are currently selected. The actual selected mappings are stored separately in the selectedFieldMappings property.
type DynamicMappingsInput = []DynamicMappingsInputEntry

// DynamicMappingsInputEntry defines model for DynamicMappingsInputEntry.
type DynamicMappingsInputEntry struct {
	// FieldName The name of the field in SaaS provider, if present, then we will not prompt the user to map the field.
	FieldName *string `json:"fieldName,omitempty"`

	// MapToDisplayName Optional display name of the field to show the user in the mapping UI.
	MapToDisplayName *string `json:"mapToDisplayName,omitempty"`

	// MapToName The name of the field in your application.
	MapToName string `json:"mapToName"`

	// MappedValues If you would like the user to map a set of possible values, this is the list of possible values of the field in your application.
	MappedValues *[]DynamicMappingsInputMappedValue `json:"mappedValues,omitempty"`

	// Prompt Optional prompt to show the user in the mapping UI.
	Prompt *string `json:"prompt,omitempty"`
}

// DynamicMappingsInputMappedValue defines model for DynamicMappingsInputMappedValue.
type DynamicMappingsInputMappedValue struct {
	MappedDisplayValue string `json:"mappedDisplayValue"`
	MappedValue        string `json:"mappedValue"`
}

// FieldSetting defines model for FieldSetting.
type FieldSetting struct {
	// Default Only use one of stringValue, integerValue, booleanValue.
	Default *FieldSettingDefault `json:"default,omitempty"`

	// WriteOnCreate Whether the default value should be applied when creating a record.
	WriteOnCreate FieldSettingWriteOnCreate `json:"writeOnCreate,omitempty"`

	// WriteOnUpdate Whether the default value should be applied when updating a record.
	WriteOnUpdate FieldSettingWriteOnUpdate `json:"writeOnUpdate,omitempty"`
}

// FieldSettingWriteOnCreate Whether the default value should be applied when creating a record.
type FieldSettingWriteOnCreate string

// FieldSettingWriteOnUpdate Whether the default value should be applied when updating a record.
type FieldSettingWriteOnUpdate string

// FieldSettingDefault Only use one of stringValue, integerValue, booleanValue.
type FieldSettingDefault struct {
	// BooleanValue The default boolean value to apply to a field
	BooleanValue *bool `json:"booleanValue,omitempty"`

	// IntegerValue The default integer value to apply to a field
	IntegerValue *int `json:"integerValue,omitempty"`

	// StringValue The default string value to apply to a field
	StringValue *string `json:"stringValue,omitempty"`
}

// ReadConfig defines model for ReadConfig.
type ReadConfig struct {
	Objects map[string]ReadConfigObject `json:"objects"`
}

// ReadConfigObject defines model for ReadConfigObject.
type ReadConfigObject struct {
	Backfill *BackfillConfig `json:"backfill,omitempty"`

	// Destination The name of the destination that the result should be sent to.
	Destination string `json:"destination,omitempty"`

	// Disabled If this flag is set to true, scheduled reads associated with this object will be paused, and on-demand reads will not be allowed.
	Disabled *bool `json:"disabled,omitempty"`

	// DynamicMappingsInput An array containing all available dynamic field and value mappings for this installation, provided by the InstallIntegration component. This array represents the complete set of possible mappings, regardless of which ones are currently selected. The actual selected mappings are stored separately in the selectedFieldMappings property.
	DynamicMappingsInput *DynamicMappingsInput `json:"dynamicMappingsInput,omitempty"`

	// ObjectName The name of the object to read from.
	ObjectName string `json:"objectName" validate:"required"`

	// Schedule The schedule for reading the object, in cron syntax.
	Schedule string `json:"schedule,omitempty"`

	// SelectedFieldMappings This is a map of mapToNames to field names. (A mapTo name is the name the builder wants to map a field to when it lands in their destination.)
	SelectedFieldMappings map[string]string `json:"selectedFieldMappings"`

	// SelectedFields This is a map of field names to booleans indicating whether they should be read. If a field is already included in `selectedFieldMappings`, it does not need to be included here.
	SelectedFields map[string]bool `json:"selectedFields"`

	// SelectedFieldsAuto If selectedFieldsAuto is set to all, all fields will be read.
	SelectedFieldsAuto *SelectedFieldsAutoConfig `json:"selectedFieldsAuto,omitempty"`

	// SelectedValueMappings This is a map of field names to their value mappings.
	SelectedValueMappings map[string]SelectedValueMappings `json:"selectedValueMappings,omitempty"`
}

// SelectedFieldsAutoConfig If selectedFieldsAuto is set to all, all fields will be read.
type SelectedFieldsAutoConfig string

// SelectedValueMappings This is a map of values to their mappings. The key is the value delivered to the webhook, the value is the value coming from the provider API.
type SelectedValueMappings map[string]string

// SubscribeConfig defines model for SubscribeConfig.
type SubscribeConfig struct {
	Objects map[string]SubscribeConfigObject `json:"objects"`
}

// SubscribeConfigObject defines model for SubscribeConfigObject.
type SubscribeConfigObject struct {
	CreateEvent *ConfigCreateEvent `json:"createEvent,omitempty"`
	DeleteEvent *ConfigDeleteEvent `json:"deleteEvent,omitempty"`

	// Destination The name of the destination that the result should be sent to.
	Destination string `json:"destination"`

	// InheritFieldsAndMappings Whether to inherit fields and mappings from the read config.
	InheritFieldsAndMappings bool `json:"inheritFieldsAndMappings"`

	// ObjectName The name of the object to subscribe to.
	ObjectName  string             `json:"objectName" validate:"required"`
	UpdateEvent *ConfigUpdateEvent `json:"updateEvent,omitempty"`
}

// UpdateInstallationConfigContent defines model for UpdateInstallationConfigContent.
type UpdateInstallationConfigContent = BaseConfigContent

// UpdateInstallationReadConfig defines model for UpdateInstallationReadConfig.
type UpdateInstallationReadConfig = BaseReadConfig

// UpdateInstallationReadConfigObject defines model for UpdateInstallationReadConfigObject.
type UpdateInstallationReadConfigObject = BaseReadConfigObject

// ValueDefault defines model for ValueDefault.
type ValueDefault = any

// ValueDefaultBoolean defines model for ValueDefaultBoolean.
type ValueDefaultBoolean struct {
	// ApplyOnUpdate Whether the default value should be applied when updating a record.
	// If set to `always`, the default value will be applied when updating a record.
	// If set to `never`, the default value will not be applied when updating a record,
	// only when creating a record.
	// If unspecified, then `always` is assumed.
	ApplyOnUpdate *ValueDefaultBooleanApplyOnUpdate `json:"applyOnUpdate,omitempty"`

	// Value The value to be used as a default.
	Value bool `json:"value"`
}

// ValueDefaultBooleanApplyOnUpdate Whether the default value should be applied when updating a record.
// If set to `always`, the default value will be applied when updating a record.
// If set to `never`, the default value will not be applied when updating a record,
// only when creating a record.
// If unspecified, then `always` is assumed.
type ValueDefaultBooleanApplyOnUpdate string

// ValueDefaultInteger defines model for ValueDefaultInteger.
type ValueDefaultInteger struct {
	// ApplyOnUpdate Whether the default value should be applied when updating a record.
	// If set to `always`, the default value will be applied when updating a record.
	// If set to `never`, the default value will not be applied when updating a record,
	// only when creating a record.
	// If unspecified, then `always` is assumed.
	ApplyOnUpdate *ValueDefaultIntegerApplyOnUpdate `json:"applyOnUpdate,omitempty"`

	// Value The value to be used as a default.
	Value int `json:"value"`
}

// ValueDefaultIntegerApplyOnUpdate Whether the default value should be applied when updating a record.
// If set to `always`, the default value will be applied when updating a record.
// If set to `never`, the default value will not be applied when updating a record,
// only when creating a record.
// If unspecified, then `always` is assumed.
type ValueDefaultIntegerApplyOnUpdate string

// ValueDefaultString defines model for ValueDefaultString.
type ValueDefaultString struct {
	// ApplyOnUpdate Whether the default value should be applied when updating a record.
	// If set to `always`, the default value will be applied when updating a record.
	// If set to `never`, the default value will not be applied when updating a record,
	// only when creating a record.
	// If unspecified, then `always` is assumed.
	ApplyOnUpdate *ValueDefaultStringApplyOnUpdate `json:"applyOnUpdate,omitempty"`

	// Value The value to be used as a default.
	Value string `json:"value"`
}

// ValueDefaultStringApplyOnUpdate Whether the default value should be applied when updating a record.
// If set to `always`, the default value will be applied when updating a record.
// If set to `never`, the default value will not be applied when updating a record,
// only when creating a record.
// If unspecified, then `always` is assumed.
type ValueDefaultStringApplyOnUpdate string

// WriteConfig defines model for WriteConfig.
type WriteConfig struct {
	Objects *map[string]WriteConfigObject `json:"objects,omitempty"`
}

// WriteConfigObject defines model for WriteConfigObject.
type WriteConfigObject struct {
	// ObjectName The name of the object to write to.
	ObjectName string `json:"objectName" validate:"required"`

	// SelectedFieldSettings This is a map of field names to their settings.
	SelectedFieldSettings map[string]FieldSetting `json:"selectedFieldSettings,omitempty"`

	// SelectedValueDefaults This is a map of field names to default values. These values will be used when writing to the object.
	// Deprecated: this property has been marked as deprecated upstream, but no `x-deprecated-reason` was set
	SelectedValueDefaults map[string]ValueDefault `json:"selectedValueDefaults,omitempty"`
}
